ALTER TABLE "AiPromptConfig" ADD COLUMN "enableTriage" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AiPromptConfig" ADD COLUMN "enableN1" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AiPromptConfig" ADD COLUMN "enableN2" BOOLEAN NOT NULL DEFAULT true;
