import { Injectable, Logger } from '@nestjs/common';
import { Octokit } from '@octokit/rest';

export interface GitAutomationSettings {
  branchFormat?: string; // default: "agent/ticket-{shortId}/{slug}"
  commitAuthor?: {
    name?: string; // default: "Support Helper Agent"
    email?: string; // default: "agent@supporthelper.io"
  };
}

export interface CreateBranchParams {
  octokit: Octokit;
  owner: string;
  repo: string;
  defaultBranch: string;
  ticketId: string;
  ticketTitle: string;
  settings?: GitAutomationSettings;
}

export interface CreateBranchResult {
  branchName: string;
  baseSha: string;
}

export interface AtomicCommitParams {
  octokit: Octokit;
  owner: string;
  repo: string;
  branchName: string;
  baseSha: string;
  files: Array<{
    filePath: string;
    content: string;
    operation: 'modify' | 'create' | 'delete';
  }>;
  ticketId: string;
  ticketTitle: string;
  agentTaskId: string;
  changeType?: string;
  settings?: GitAutomationSettings;
}

export interface AtomicCommitResult {
  commitSha: string;
  filesCommitted: number;
}

@Injectable()
export class GitAutomationService {
  private readonly logger = new Logger(GitAutomationService.name);

  async createBranch(
    params: CreateBranchParams,
  ): Promise<CreateBranchResult> {
    const {
      octokit,
      owner,
      repo,
      defaultBranch,
      ticketId,
      ticketTitle,
    } = params;

    // Get HEAD SHA of the default branch
    const { data: refData } = await octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });
    const baseSha = refData.object.sha;

    // Build branch name
    const shortId = ticketId.substring(0, 8);
    const slug = this.slugify(ticketTitle);
    let branchName = `agent/ticket-${shortId}/${slug}`;

    try {
      await octokit.git.createRef({
        owner,
        repo,
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      });
    } catch (error: unknown) {
      const status = (error as { status?: number })?.status;
      if (status === 409 || status === 422) {
        // Branch already exists — retry with timestamp suffix
        const timestamp = Date.now();
        branchName = `agent/ticket-${shortId}/${slug}-${timestamp}`;
        this.logger.warn(
          `Branch already exists, retrying as ${branchName}`,
        );
        await octokit.git.createRef({
          owner,
          repo,
          ref: `refs/heads/${branchName}`,
          sha: baseSha,
        });
      } else {
        throw error;
      }
    }

    this.logger.log(
      `Created branch ${branchName} from ${defaultBranch} (${baseSha.substring(0, 7)})`,
    );

    return { branchName, baseSha };
  }

  async atomicCommit(
    params: AtomicCommitParams,
  ): Promise<AtomicCommitResult> {
    const {
      octokit,
      owner,
      repo,
      branchName,
      baseSha,
      files,
      ticketId,
      ticketTitle,
      agentTaskId,
      changeType,
      settings,
    } = params;

    // Build tree entries
    const treeEntries: Array<{
      path: string;
      mode: '100644';
      type: 'blob';
      sha: string | null;
    }> = [];

    for (const file of files) {
      if (file.operation === 'delete') {
        treeEntries.push({
          path: file.filePath,
          mode: '100644',
          type: 'blob',
          sha: null,
        });
      } else {
        const { data: blobData } = await octokit.git.createBlob({
          owner,
          repo,
          content: file.content,
          encoding: 'utf-8',
        });
        treeEntries.push({
          path: file.filePath,
          mode: '100644',
          type: 'blob',
          sha: blobData.sha,
        });
      }
    }

    // Create tree
    const { data: treeData } = await octokit.git.createTree({
      owner,
      repo,
      base_tree: baseSha,
      tree: treeEntries as Array<{ path: string; mode: '100644'; type: 'blob'; sha: string | null }>,
    });

    // Build commit message in conventional format
    const commitPrefix = changeType === 'bug_fix' ? 'fix' : 'feat';
    const title = ticketTitle || 'AI-generated changes';
    const commitMessage = [
      `${commitPrefix}: ${title}`,
      '',
      `Ticket: ${ticketId}`,
      `Agent-Task: ${agentTaskId}`,
      '',
      'Generated by Support Helper AI Agent',
    ].join('\n');

    // Author info
    const authorName =
      settings?.commitAuthor?.name || 'Support Helper Agent';
    const authorEmail =
      settings?.commitAuthor?.email || 'agent@supporthelper.io';

    // Create commit
    const { data: commitData } = await octokit.git.createCommit({
      owner,
      repo,
      message: commitMessage,
      tree: treeData.sha,
      parents: [baseSha],
      author: {
        name: authorName,
        email: authorEmail,
      },
    });

    // Update branch ref to point at the new commit
    await octokit.git.updateRef({
      owner,
      repo,
      ref: `heads/${branchName}`,
      sha: commitData.sha,
    });

    this.logger.log(
      `Committed ${files.length} files to ${branchName} (${commitData.sha.substring(0, 7)})`,
    );

    return {
      commitSha: commitData.sha,
      filesCommitted: files.length,
    };
  }

  private slugify(title: string, maxLength = 50): string {
    return title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/-{2,}/g, '-')
      .replace(/^-+|-+$/g, '')
      .substring(0, maxLength)
      .replace(/-+$/, '');
  }
}
