import { Injectable, Logger } from '@nestjs/common';
import { Octokit } from '@octokit/rest';

export interface CreateOrUpdatePRParams {
  octokit: Octokit;
  owner: string;
  repo: string;
  branchName: string;
  defaultBranch: string;
  ticketId: string;
  ticket: {
    title?: string;
    description?: string;
    type?: string;
    severity?: string;
    aiSummary?: string;
  };
  actionPlan: {
    summary: string;
    rootCause: string;
    testingStrategy?: string;
    files: Array<{
      filePath: string;
      operation: string;
      description: string;
    }>;
  };
  generatedFiles: Array<{
    filePath: string;
    operation: string;
  }>;
  agentTaskId: string;
  settings?: PRSettings;
}

export interface PRSettings {
  reviewers?: string[];
  autoLabel?: boolean; // default: true
}

export interface CreateOrUpdatePRResult {
  prNumber: number;
  prUrl: string;
  created: boolean; // true if new, false if updated
}

@Injectable()
export class PullRequestService {
  private readonly logger = new Logger(PullRequestService.name);

  async createOrUpdatePR(
    params: CreateOrUpdatePRParams,
  ): Promise<CreateOrUpdatePRResult> {
    const {
      octokit,
      owner,
      repo,
      branchName,
      defaultBranch,
      ticketId,
      ticket,
      actionPlan,
      agentTaskId,
      settings,
    } = params;

    const title = this.buildTitle(ticket);
    const body = this.buildPRBody({
      ticketId,
      ticket,
      actionPlan,
      agentTaskId,
    });

    // Check for existing open PR on same branch
    const { data: existingPRs } = await octokit.pulls.list({
      owner,
      repo,
      head: `${owner}:${branchName}`,
      state: 'open',
    });

    let prNumber: number;
    let prUrl: string;
    let created: boolean;

    if (existingPRs.length > 0) {
      // Update existing PR
      const existingPR = existingPRs[0]!;
      const { data: updatedPR } = await octokit.pulls.update({
        owner,
        repo,
        pull_number: existingPR.number,
        title,
        body,
      });

      prNumber = updatedPR.number;
      prUrl = updatedPR.html_url;
      created = false;

      this.logger.log(
        `Updated existing PR #${prNumber} in ${owner}/${repo}`,
      );
    } else {
      // Create new PR
      const { data: newPR } = await octokit.pulls.create({
        owner,
        repo,
        title,
        body,
        head: branchName,
        base: defaultBranch,
      });

      prNumber = newPR.number;
      prUrl = newPR.html_url;
      created = true;

      this.logger.log(
        `Created PR #${prNumber} in ${owner}/${repo}`,
      );
    }

    // Add labels (default: enabled)
    const autoLabel = settings?.autoLabel !== false;
    if (autoLabel) {
      await this.addLabels(octokit, owner, repo, prNumber, ticket);
    }

    // Assign reviewers
    await this.assignReviewers(
      octokit,
      owner,
      repo,
      prNumber,
      settings?.reviewers,
    );

    return { prNumber, prUrl, created };
  }

  private buildTitle(ticket: CreateOrUpdatePRParams['ticket']): string {
    const prefix = ticket.type === 'bug' ? 'fix' : 'feat';
    const title = ticket.title || 'AI-generated changes';
    const full = `${prefix}: ${title}`;
    return full.length > 100 ? full.substring(0, 97) + '...' : full;
  }

  private buildPRBody(params: {
    ticketId: string;
    ticket: CreateOrUpdatePRParams['ticket'];
    actionPlan: CreateOrUpdatePRParams['actionPlan'];
    agentTaskId: string;
  }): string {
    const { ticketId, ticket, actionPlan, agentTaskId } = params;

    const changesTable = actionPlan.files
      .map(
        (f) =>
          `| \`${f.filePath}\` | ${f.operation} | ${f.description} |`,
      )
      .join('\n');

    const testingStrategy =
      actionPlan.testingStrategy || 'Manual verification recommended.';

    return [
      '## Summary',
      '',
      actionPlan.summary,
      '',
      '## Root Cause',
      '',
      actionPlan.rootCause,
      '',
      '## Changes',
      '',
      '| File | Operation | Description |',
      '|------|-----------|-------------|',
      changesTable,
      '',
      '## Testing Strategy',
      '',
      testingStrategy,
      '',
      '## Ticket Details',
      '',
      `- **Ticket ID:** \`${ticketId}\``,
      `- **Type:** ${ticket.type || 'Unknown'}`,
      `- **Severity:** ${ticket.severity || 'Unknown'}`,
      `- **AI Summary:** ${ticket.aiSummary || 'N/A'}`,
      '',
      '---',
      '*Generated by Support Helper AI Agent*  ',
      `*Agent Task: \`${agentTaskId}\`*`,
    ].join('\n');
  }

  private async addLabels(
    octokit: Octokit,
    owner: string,
    repo: string,
    prNumber: number,
    ticket: CreateOrUpdatePRParams['ticket'],
  ): Promise<void> {
    const labelDefs: Array<{ name: string; color: string }> = [
      { name: 'agent-generated', color: '7B61FF' },
    ];

    if (ticket.severity) {
      const severityColors: Record<string, string> = {
        critical: 'DC2626',
        high: 'F59E0B',
        medium: '3B82F6',
        low: '22C55E',
      };
      labelDefs.push({
        name: `severity:${ticket.severity}`,
        color: severityColors[ticket.severity] || '6B7280',
      });
    }

    if (ticket.type) {
      labelDefs.push({
        name: `type:${ticket.type}`,
        color: '6366F1',
      });
    }

    // Ensure each label exists in the repository
    for (const label of labelDefs) {
      try {
        await octokit.issues.createLabel({
          owner,
          repo,
          name: label.name,
          color: label.color,
        });
      } catch (error: any) {
        // 422 means label already exists — that's fine
        if (error?.status !== 422) {
          this.logger.warn(
            `Failed to create label "${label.name}": ${error?.message}`,
          );
        }
      }
    }

    // Add all labels to the PR
    const labelNames = labelDefs.map((l) => l.name);
    try {
      await octokit.issues.addLabels({
        owner,
        repo,
        issue_number: prNumber,
        labels: labelNames,
      });
      this.logger.log(
        `Added labels [${labelNames.join(', ')}] to PR #${prNumber}`,
      );
    } catch (error: any) {
      this.logger.warn(
        `Failed to add labels to PR #${prNumber}: ${error?.message}`,
      );
    }
  }

  private async assignReviewers(
    octokit: Octokit,
    owner: string,
    repo: string,
    prNumber: number,
    reviewers?: string[],
  ): Promise<void> {
    if (!reviewers || reviewers.length === 0) {
      return;
    }

    try {
      await octokit.pulls.requestReviewers({
        owner,
        repo,
        pull_number: prNumber,
        reviewers,
      });
      this.logger.log(
        `Assigned reviewers [${reviewers.join(', ')}] to PR #${prNumber}`,
      );
    } catch (error: any) {
      this.logger.warn(
        `Failed to assign reviewers to PR #${prNumber}: ${error?.message}`,
      );
    }
  }
}
