// Development/test RSA public key for license verification
// In production, replace with your actual public key
export const LICENSE_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0Z3VS5JKxnRaEWLqWMHg
kSNrIBFPSCOlNM4YBxXVSxNqZb7G5g8nQRFGHXJzmVFDT0WP8nKTXLRJSj7VRXKF
dSl7MQBKzO3JhOiU8rDZbs7q/Ij7Y0hy7gE+FKrBjQzIYYKXXKhAsWvGBftMEz0w
x3NKy0p7QDxsaL7FCCB75bpNJgJiQ4x7VpeFg42jVn1DhJxsjmGGjJMn/4ZIZRHR
q6C5oRi9Xnv8oFbIJCeQTPITz9sGXlgbhKgUZL43r6VSAaE2A7MaRNLWxFzy8rOn
6GdVIbIQmVN0VEfBP3R/onMD5xGJKaXUaGp1szhnmDpcJnD0C2FyUx0oaTXhR/lT
3QIDAQAB
-----END PUBLIC KEY-----`;
